### ISSUE TITLE
Create `user.md` file

### ISSUE THREAD

**Issue by malak-coforma** [coforma-acme/acme-tech-challenge#106]
## Description

This file should contain instructions for how to use the API endpoints

## Requirements

- [ ] Link to the OpenAPI documentation
- [ ] Step-by-step instructions on how to use the OpenAPI docs to generate JWT token and then use that to Authorize (we can include screenshots in here if needed)
- [ ] Table of available facility IDs (can take formatting from below)
- [ ] Table of available status IDs (can take formatting from below)
- [ ] Table of available disaster IDs (can take formatting from below)

#### Markdown

```
|`___Id`|Name|
|---|---|
|`0`|Care Facility 1|
|`1`|Care Facility 2|
```

#### Example results

|`facilityNpi`|Facility Name|
|---|---|
|`0`|Care Facility 1|
|`1`|Care Facility 2|

|`statusId`|Status Name|
|---|---|
|`0`|unaffected|
|`1`|ill in facility|

|`disasterId`|Disaster Name|
|---|---|
|`0`|Disaster 1|
|`1`|Disaster 2|

## Next Steps

- [ ] Link to it from the `README.md` because we're nice people

## Tech Notes

**Comment by TheDanMiller** [comment]
Done
