### ISSUE TITLE
Facility Data Model

### ISSUE THREAD

**Issue by malak-coforma** [coforma-acme/acme-tech-challenge#14]
## Description

| | |
|---|---|
|Endpoint|n/a|
|Method|n/a|
|Roles|n/a|

This is a model that supports other endpoints. We will be using a hard-coded list of facilities that we will seed with. 

Currently thinking code-first, but if we want to seed the data via an automated method then we should create a follow-up ticket to implement that.

Tables to be created: `Facility` and `StateCodes`.

## Acceptance Criteria

1. Database table is formed
2. Migration exists for database table
3. Seed the data into the table

## Documentation Opportunities

- [ ] Update install and configure script in `README.md`
- [ ] Create ticket for automated update, any decisions around doing/not doing that

## Tech Notes

Hibernate will read a seed file and create tables if they don't exist and then also populate. If this doesn't go well, @wellsstephen is okay with scripting it all out if needed. 😬 

### Database fields

[Overall schema plan (Lucidchart)](https://lucid.app/lucidchart/9c9d59a1-2256-475b-b022-ea09e412add1/edit?viewport_loc=-1616%2C-305%2C2827%2C1440%2CsafEAJR_tvNv&invitationId=inv_5bd3d19f-e184-47bf-b7f6-8b8c829d453d#)

![Image](https://user-images.githubusercontent.com/102534056/182714830-3809fc57-bebb-4e51-99f7-bd10b2291e89.png)

**Comment by TheDanMiller** [comment]
data is seeded
