### ISSUE TITLE
Disaster Data Model

### ISSUE THREAD

**Issue by malak-coforma** [coforma-acme/acme-tech-challenge#19]
## Description

This is the data models for disasters

we want to seed the data via an automated method -- we should create a follow-up ticket to implement that.

This does include seeding the lookup tables

## User Story

Not a user facing ticket -- tech only

## Acceptance Criteria

1. Disaster Data Model exists
3. Migration exists for DB
4. Seed ten disasters (see Tech Notes section)

## Documentation Opportunities

- [ ] Modeled disaster information around fema declared disasters page [https://www.fema.gov/disaster/declarations?field_dv2_state_territory_tribal_value=All&field_dv2_declaration_type_value=All&field_dv2_incident_type_target_id_selective=All](https://www.fema.gov/disaster/declarations?field_dv2_state_territory_tribal_value=All&field_dv2_declaration_type_value=All&field_dv2_incident_type_target_id_selective=All)

## Next Steps

- [ ] Create follow up ticket to seed data via automated method.

## Tech Notes

Hibernate will read a seed file and create tables if they don't exist and then also populate. If this doesn't go well, @wellsstephen is okay with scripting it all out if needed. 😬 

### Sample disaster seed data:

```
[
  {
    name: "South Dakota Severe Storm, Straight-line Winds, Tornadoes, and Flooding (DR-4664-SD)",
    startDate: 2022-06-11T16:55:14+0000,
    endDate: 2022-06-14T16:55:14+0000,
    declarationType: 0,
  },
  {
    name: "Kentucky Severe Storms, Flooding, Landslides, and Mudslides (DR-4663-KY)",
    startDate: 2022-07-26T16:55:14+0000,
    endDate: null,
    declarationType: 0,
  },
  {
    name: "Nebraska Severe Storms and Straight-line Winds (DR-4662-NE)",
    startDate: 2022-05-12T16:55:14+0000,
    endDate: 2022-05-12T16:55:14+0000,
    declarationType: 0,
  },
  {
    name: "Virgin Islands Water Shortage and Health Impact From Unprecedented Sargassum Seagrass Influx (EM-3581-VI)",
    startDate: 2022-07-15T16:55:14+0000,
    endDate: null,
    declarationType: 1,
  },
  {
    name: "California Oak Fire (FM-5445-CA)",
    startDate: 2022-07-22T16:55:14+0000,
    endDate: null,
    declarationType: 2,
  },
  {
    name: "California Oak Fire (FM-5445-CA)",
    startDate: 2022-07-18T16:55:14+0000,
    endDate: null,
    declarationType: 2,
  },
  {
    name: "North Dakota Severe Winter Storm and Flooding (DR-4660-ND)",
    startDate: 2022-04-22T16:55:14+0000,
    endDate: 2022-04-25T16:55:14+0000,
    declarationType: 0,
  },
  {
    name: "Minnesota Severe Storms, Straight-line Winds, and Flooding (DR-4659-MN)",
    startDate: 2022-04-22T16:55:14+0000,
    endDate: 2022-06-15T16:55:14+0000,
    declarationType: 0,
  },
  {
    name: "Arizona Pipeline Fire (FM-5441-AZ)",
    startDate: 2022-06-12T16:55:14+0000,
    endDate: null,
    declarationType: 0,
  },
  {
    name: "Louisiana Tropical Storm Nicholas (EM-3574-LA)",
    startDate: 2021-09-12T16:55:14+0000,
    endDate: 2021-09-13T16:55:14+0000,
    declarationType: 1,
  },
]
```

### Sample `declarationType` data:

```
[
  {
    id: 0,
    name: "Major Disaster Declaration",
  },
  {
    id: 1,
    name: "Emergency Declaration",
  },
  {
    id: 2,
    name: "Fire Management Assistance Declaration",
  },
  {
    id: 3,
    name: "Fire Suppression Authorization",
  },
]
```

### Database fields

[Overall schema plan (Lucidchart)](https://lucid.app/lucidchart/9c9d59a1-2256-475b-b022-ea09e412add1/edit?view_items=X5AEgo5N.ieC&invitationId=inv_5bd3d19f-e184-47bf-b7f6-8b8c829d453d#)

![Image](https://user-images.githubusercontent.com/102534056/182862134-803e429f-e32b-4d9f-96cf-e3313e544243.png)

**Comment by TheDanMiller** [comment]
data is seeded
