### ISSUE TITLE
Get summary of a facility's patient impact by disaster

### ISSUE THREAD

**Issue by malak-coforma** [coforma-acme/acme-tech-challenge#36]
## Description

| | |
|---|---|
|Endpoint|`acme/disaster`|
|Method|`GET`|
|Possible Parameters|`facilityNpi` (`int`), `disasterId` (`int`)|
|Roles|Government Systems Coordinator, Facility System Administrator|

Summarize a facility's impact to patients by specific disaster.

### User Story

**As a** Government Systems Coordinator or Facility System Administrator
**I want** to see a summary of patient impact data for a disaster
**So that** I can get a "big picture" view of a facility
**Because** I need to monitor overall quality of care for patients during a disaster.

## GET Parameters

|Parameter|Data Type|Optional?|
|---|---|---|
|`facilityNpi`|`int`|OPTIONAL|
|`disasterId`|`int`|REQUIRED|
|`state`|`int`|OPTIONAL|
|`timeFrame`|`string(yyyymmdd)`|OPTIONAL|
|`status`|`int`|OPTIONAL|

### 200

```
{
  "unaffected": int,
  "injured": int,
  "illInFacility": int,
  "illNotInFacility": int,
  "deceased": int,
  "isolated": int,
}
```

### 400

If request body sent is syntactically invalid.

If request body sent is not processable (missing or malformed data).

### 403

This endpoint is not authorized for roles who are not Government Systems Coordinators or Facility System Administrators.

## Acceptance Criteria

1. Returns `200` with response body when well-formatted data is sent by a Government Systems Coordinators or Facility System Administrators.
2. Returns `400` if request body is malformed.
3. Returns `400` if request body is missing required data.
4. Returns `400` if the request body contains data that doesn't make sense.
5. Returns `403` if request is made by a role other than a Government Systems Coordinators or Facility System Administrators.

## Tech Notes

[Overall schema plan (Lucidchart)](https://lucid.app/lucidchart/9c9d59a1-2256-475b-b022-ea09e412add1/edit?invitationId=inv_5bd3d19f-e184-47bf-b7f6-8b8c829d453d&page=h3gEAyswjezV#)

![Image](https://user-images.githubusercontent.com/102534056/182897063-9089e4d7-f3df-40e6-a4f3-e57dc41872a2.png)

**Comment by BearHanded** [comment]
Disaster impact summary (/disaster) (GET): 
* When accessed by the FSA, this endpoint summarizes the numbers of patients with each type of patient status at the FSA’s facility, as of the most recent update

* When accessed by the GCSC, this endpoint summarizes the numbers of patients with each type of patient status across multiple facilities by disaster, geographic state, date range, patient status, or facility as of The most recent update

**Comment by malak-coforma** [comment]
Hey @BearHanded -- was the multiple facilities bit implemented here? Having a hard time going through the code on the PR and seeing that multiple facilities were able to be summarized. 🤔
