### ISSUE TITLE
Create AWS "uninstall" script

### ISSUE THREAD

**Issue by malak-coforma** [coforma-acme/acme-tech-challenge#51]
## Description

We need to provide a way to uninstall our solution from AWS.

## Requirements

- [ ] A script to uninstall our solution

## Next Steps

- [ ] Update documentation in #24 

## Tech Notes

**Comment by malak-coforma** [comment]
Probably just call `terraform destroy` -- not anticipating any extra steps.

**Comment by TheDanMiller** [comment]
done
